### ISSUE TITLE
gitalk network error 个人博客问题兼容 | 新时代农民工的日常

### ISSUE THREAD

**Issue by whu-ranky** [whu-ranky/blog-comment#18]
https://pinkcle.com/blog/gitalk.html 

 记录点滴，分享所有~

**Comment by Ikun-CYX** [comment]
111

**Comment by whu-ranky** [comment]
——Your Email has been received. Thank you!
        By WuHan University 
         Computer College.
           Hao Xiong.

**Comment by SLQ1893** [comment]
hello

**Comment by whu-ranky** [comment]
——Your Email has been received. Thank you!
        By WuHan University 
         Computer College.
           Hao Xiong.

**Comment by Anohimono** [comment]
hello

**Comment by ChenyCHENYU** [comment]
测试了貌似不行额

**Comment by whu-ranky** [comment]
> @ChenyCHENYU
> 测试了貌似不行额

具体错误是啥呢？

**Comment by ChenyCHENYU** [comment]
哈哈，作者你好，能否给我个QQ联系方式，我加你沟通方便一些

**Comment by DoAutumn** [comment]
<img width="1445" alt="截屏2023-01-13 18 20 47" src="https://user-images.githubusercontent.com/122422382/212296982-39914473-9d97-4406-8491-a3fcbc0adaa9.png">

**Comment by whu-ranky** [comment]
> @DoAutumn
> <img width="1445" alt="截屏2023-01-13 18 20 47" src="https://user-images.githubusercontent.com/122422382/212296982-39914473-9d97-4406-8491-a3fcbc0adaa9.png">
> 

呃... 你这个不是评论了吗，504 GateWay timeout

**Comment by DoAutumn** [comment]
> > @DoAutumn
> > <img alt="截屏2023-01-13 18 20 47" width="1445" src="https://user-images.githubusercontent.com/122422382/212296982-39914473-9d97-4406-8491-a3fcbc0adaa9.png">
> 
> 呃... 你这个不是评论了吗，504 GateWay timeout

我这是直接在github的issues上提的，不是在博客上

**Comment by whu-ranky** [comment]
> @DoAutumn
> > > @DoAutumn
> > > <img alt="截屏2023-01-13 18 20 47" width="1445" src="https://user-images.githubusercontent.com/122422382/212296982-39914473-9d97-4406-8491-a3fcbc0adaa9.png">
> > 
> > 呃... 你这个不是评论了吗，504 GateWay timeout
> 
> 我这是直接在github的issues上提的，不是在博客上

在有限制的比如公司网络吗？get_accesstoken是我个人服务器的api，不应该出现504...

**Comment by DoAutumn** [comment]
> @whu-ranky
> > @DoAutumn
> > > > @DoAutumn
> > > > <img alt="截屏2023-01-13 18 20 47" width="1445" src="https://user-images.githubusercontent.com/122422382/212296982-39914473-9d97-4406-8491-a3fcbc0adaa9.png">
> > > 
> > > 呃... 你这个不是评论了吗，504 GateWay timeout
> > 
> > 我这是直接在github的issues上提的，不是在博客上
> 
> 在有限制的比如公司网络吗？get_accesstoken是我个人服务器的api，不应该出现504...

确实是，不好意思

**Comment by Hrviun** [comment]
1

**Comment by Leaovo-man2** [comment]
# 我的还是error

**Comment by Leaovo-man2** [comment]
提示错误：未找到相关的 Issues 进行评论

请联系 @xxx 初始化创建

使用 GitHub 登录

登陆后显示Network Error

**Comment by whu-ranky** [comment]
> @Leaovo-man2
> 提示错误：未找到相关的 Issues 进行评论
> 
> 请联系 @xxx 初始化创建
> 
> 使用 GitHub 登录
> 
> 登陆后显示Network

可以打开控制台贴下错误的详细信息哈?

**Comment by Leaovo-man2** [comment]
ajax.googleapis.com/ajax/libs/webfont/1.5.18/webfont.js:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
gitalk.jsx:128 err:  Error: Network Error
    at e.exports (createError.js:16:15)
    at f.onerror (xhr.js:83:14)
cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token:1 
        
        
        Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by Leaovo-man2** [comment]
Time out了，听他们说要kx上w，
该怎么办？你是用的kx上w吗？😶,指点下`(*>﹏<*)′。

**Comment by whu-ranky** [comment]
> @Leaovo-man2
> ajax.googleapis.com/ajax/libs/webfont/1.5.18/webfont.js:1 
>         
>         
>         Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
> gitalk.jsx:128 err:  Error: Network Error
>     at e.exports (createError.js:16:15)
>     at f.onerror (xhr.js:83:14)
> cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token:1 
>         
>         
>         Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
> 

这应该是代理没生效，gitalk的请求还是到https://cors-anywhere.azm.workers.dev了

**Comment by Leaovo-man2** [comment]
我不太明白那篇文章，请问
_代理要写在哪里_
仓库：https://github.com/Leaovo-man2/Leaovo-man2.github.io
（我只会Python和md😭）
可以详细说一下吗

**Comment by Leaovo-man2** [comment]
是把

`proxy: 'https://proxy'`
加在Gitalk.html的
```
    const gitalk = new Gitalk({
      这里
    })
```
吗

**Comment by whu-ranky** [comment]
> @Leaovo-man2
> 是把
> 
> `proxy: 'https://proxy'`
> 加在Gitalk.html的
> ```
>     const gitalk = new Gitalk({
>       这里
>     })
> ```
> 吗

看了下你的仓库，不是加https://proxy 这个文本。 我的文章意思是https://{proxy}， proxy是你的代理服务器地址，如 127.0.0.1 （https|http://127.0.0.1）, 或者你的代理服务器的域名(https|http://sample.com)，gitalk会向这个代理服务器获取github accesstoken的请求。

之前的https://cors-anywhere.azm.workers.dev 这个代理地址是gitalk自己的用不了，所以需要一层代理，国内可以访问github auth2 api，所以可以替换为国内的服务器地址。

**Comment by Leaovo-man2** [comment]
加在最上面的文件夹Gitalk.html中，还是写在根目录的yml中

**Comment by Leaovo-man2** [comment]
代理服务器的域名是指https://IP.com ?

是指IP吗

**Comment by whu-ranky** [comment]
> @Leaovo-man2
> 代理服务器的域名是指https://IP.com ?
> 
> 是指IP吗

https://127.0.0.1 你的代理服务器ip地址

**Comment by whu-ranky** [comment]
> @Leaovo-man2
> 加在最上面的文件夹Gitalk.html中，还是写在根目录的yml中


> @Leaovo-man2
> 加在最上面的文件夹Gitalk.html中，还是写在根目录的yml中

加在实际创建gitalk对象的位置

**Comment by Leaovo-man2** [comment]
欧！
用cmd查了
默认网关. . . . . . . . . . . . . : 192.168.0.1
是他吗，网关地址

**Comment by whu-ranky** [comment]
> @Leaovo-man2
> 欧！
> 用cmd查了
> 默认网关. . . . . . . . . . . . . : 192.168.0.1
> 是他吗，网关地址

代理服务器地址，跟网关没有关系

**Comment by Leaovo-man2** [comment]
设置里只有：DNS，默认网关，IPv4地址。怎样查询？（你说的代理是科学sw？我没有）

**Comment by Leaovo-man2** [comment]
![image](https://github.com/whu-ranky/blog-comment/assets/132978937/acf672b4-7aba-436f-bae9-d1f629a9ccdc)
我在浏览器里Internet设置中发现代理服务器未开启，地址和端口都是空的

**Comment by whu-ranky** [comment]
> @Leaovo-man2
> ![image](https://github.com/whu-ranky/blog-comment/assets/132978937/acf672b4-7aba-436f-bae9-d1f629a9ccdc)
> 我在浏览器里Internet设置中发现代理服务器未开启，地址和端口都是空的

https://juejin.cn/post/7147506835594543118

找了一个代理服务器的简单介绍，你应该需要的是一个server。当然windows 也能搭建，如果你的博客是本地的话，那可以用本地代理，代理服务器地址就是127.0.0.1；如果是博客，我理解应该不是本地的，那么你就需要一个云服务器，或者你本地windows，要求不关机且固定IP，就可以用你本地机器的固定IP。

同时，你需要在代理服务器上有一个转发服务, 文章中我用的nginx左的

**Comment by Leaovo-man2** [comment]
非常感谢！我的博客已经成功配置上了Gitalk
我并没有按照文章写代理，只是在_config.yml中gitalk增加了
```
proxy: "https://strong-caramel-969805.netlify.app/github_access_token"
```
这个也可以行通
(像我一样不懂的人可以试试)

**Comment by Leaovo-man2** [comment]
配置：![image](https://github.com/whu-ranky/blog-comment/assets/132978937/5e618f7c-ef7d-4fd0-b2f0-f94e44f90d65)
![image](https://github.com/whu-ranky/blog-comment/assets/132978937/5bbe296b-d624-46aa-97bf-bcd19020161f)

**Comment by whu-ranky** [comment]
> @Leaovo-man2
> 非常感谢！我的博客已经成功配置上了Gitalk
> 我并没有按照文章写代理，只是在_config.yml中gitalk增加了
> ```
> proxy: "https://strong-caramel-969805.netlify.app/github_access_token"
> ```
> 这个也可以行通
> (像我一样不懂的人可以试试)

你这个是第三方的代理配置，也是可以用的，只是client_secret会暴露,将就用也行
